-- Data_Dict.lua - TDL-data(v1.3.0)
-- 更新说明：更新了临时地区和临时怪物的手动添加区域
TDL_Dict_Version = "1.3.0"

TDL_ZoneDict = {
-- ========== 原有条目 ==========
["The Barrens"] = "贫瘠之地",
["The Dust Plains"] = "尘泥沼泽",
["Elwynn Forest"] = "艾尔文森林",
["The Maul"] = "厄运之槌",
["Windshear Crag"] = "风剪峭壁",
["Whitereach Post"] = "白沙营地",
["Frostmane Hold"] = "霜鬃要塞",
["Ameth'Aran"] = "阿梅萨兰",
["Chillwind Point"] = "冰风岗",
["Dun Modr"] = "丹莫德",
["Ruins of Nashal'aran"] = "纳萨拉兰废墟",
["Jerod's Landing"] = "杰罗德的码头",
["Teldrassil"] = "泰达希尔",
["Silverpine Forest"] = "银松森林",

-- ========== 卡利姆多大地名 ==========
["Durotar"] = "杜隆塔尔",
["Mulgore"] = "莫高雷",
["Darkshore"] = "黑海岸",
["Stonetalon Mountains"] = "石爪山脉",
["Ashenvale"] = "灰谷",
["Thousand Needles"] = "千针石林",
["Desolace"] = "凄凉之地",
["Dustwallow Marsh"] = "尘泥沼泽",
["Feralas"] = "菲拉斯",
["Tanaris"] = "塔纳利斯",
["Un'Goro Crater"] = "安戈洛环形山",
["Azshara"] = "艾萨拉",
["Felwood"] = "费伍德森林",
["Winterspring"] = "冬泉谷",
["Moonglade"] = "月光林地",
["Silithus"] = "希利苏斯",
["Azuremyst Isle"] = "秘蓝岛",
["Bloodmyst Isle"] = "秘血岛",
["Kezan"] = "科赞",
["Lost Isles"] = "失落群岛",
["Mount Hyjal"] = "海加尔山",
["Uldum"] = "奥丹姆",

-- ========== 东部王国大地名 ==========
["Westfall"] = "西部荒野",
["Duskwood"] = "暮色森林",
["Redridge Mountains"] = "赤脊山",
["Deadwind Pass"] = "逆风小径",
["Swamp of Sorrows"] = "悲伤沼泽",
["Blasted Lands"] = "诅咒之地",
["Stranglethorn Vale"] = "荆棘谷",
["Burning Steppes"] = "燃烧平原",
["Searing Gorge"] = "灼热峡谷",
["Badlands"] = "荒芜之地",
["Dun Morogh"] = "丹莫罗",
["Loch Modan"] = "洛克莫丹",
["Wetlands"] = "湿地",
["Arathi Highlands"] = "阿拉希高地",
["Tirisfal Glades"] = "提瑞斯法林地",
["Hillsbrad Foothills"] = "希尔斯布莱德丘陵",
["Alterac Mountains"] = "奥特兰克山脉",
["The Hinterlands"] = "辛特兰",
["Western Plaguelands"] = "西瘟疫之地",
["Eastern Plaguelands"] = "东瘟疫之地",
["Eversong Woods"] = "永歌森林",
["Ghostlands"] = "幽魂之地",
["Isle of Quel'Danas"] = "奎尔丹纳斯岛",
["Gilneas"] = "吉尔尼斯",

-- ========== 原版5人副本 ==========
["Ragefire Chasm"] = "怒焰裂谷",
["Wailing Caverns"] = "哀嚎洞穴",
["Deadmines"] = "死亡矿井",
["Shadowfang Keep"] = "影牙城堡",
["Blackfathom Deeps"] = "黑暗深渊",
["Gnomeregan"] = "诺莫瑞根",
["Scarlet Monastery"] = "血色修道院",
["Razorfen Kraul"] = "剃刀沼泽",
["Razorfen Downs"] = "剃刀高地",
["Zul'Farrak"] = "祖尔法拉克",
["Maraudon"] = "玛拉顿",
["Sunken Temple"] = "阿塔哈卡神庙",
["Uldaman"] = "奥达曼",
["Dire Maul"] = "厄运之槌",
["Scholomance"] = "通灵学院",
["Stratholme"] = "斯坦索姆",
["Blackrock Depths"] = "黑石深渊",
["Lower Blackrock Spire"] = "黑石塔下层",

-- ========== 原版团队副本 ==========
["Molten Core"] = "熔火之心",
["Blackwing Lair"] = "黑翼之巢",
["Ruins of Ahn'Qiraj"] = "安其拉废墟",
["Temple of Ahn'Qiraj"] = "安其拉神庙",
["Naxxramas"] = "纳克萨玛斯",

-- ========== 乌龟服新增副本 ==========
["Moonwood Retreat"] = "新月林地",
["Storm Ruins"] = "风暴废墟",
["Dragonmaw Lair"] = "龙喉居所",
["Karazhan Crypts"] = "卡拉赞地穴",
["Windhorn Canyon"] = "风角峡谷",
["Stormwind Vault"] = "暴风城大监狱",
["Gilneas City"] = "吉尔尼斯城",
["Black Morass"] = "黑色沼泽",
["Timbermaw Hold"] = "木喉要塞",
["Emerald Sanctum"] = "翡翠圣殿",
["Foundry"] = "锻造厂",

-- ========== 乌龟服世界Boss区域 ==========
["Tanaris Colossus"] = "塔纳利斯巨人",
["Desolace Voidwalker"] = "凄凉之地虚空行者",

-- ========== 乌龟服新增大地图区域 ==========
["Thalassian Highlands"] = "萨拉斯高地",
["Brightwood Grove"] = "明木林地",

-- ========== 卡利姆多子地名（杜隆塔尔） ==========
["Orgrimmar"] = "奥格瑞玛",
["Orgrimmar The Drag"] = "奥格瑞玛 拖车区",
["Orgrimmar Valley of Honor"] = "奥格瑞玛 荣誉谷",
["Orgrimmar Valley of Spirits"] = "奥格瑞玛 精神谷",
["Orgrimmar Valley of Strength"] = "奥格瑞玛 力量谷",
["Orgrimmar Valley of Wisdom"] = "奥格瑞玛 智慧谷",
["Orgrimmar Cleft of Shadow"] = "奥格瑞玛 暗影裂隙",
["Razor Hill"] = "剃刀岭",
["Sen'jin Village"] = "森金村",
["Valley of Trials"] = "试炼谷",
["Echo Isles"] = "回音群岛",
["Darkspear Strand"] = "暗矛海滩",
["Drygulch Ravine"] = "枯水谷",
["Dustwind Cave"] = "尘风洞穴",
["Jaggedswine Farm"] = "尖猪农场",
["Kolkar Crag"] = "科尔卡石崖",
["The Den"] = "兽穴",
["Tiragarde Keep"] = "提拉加德城堡",
["Thunder Ridge"] = "雷霆山脊",
["Scuttle Coast"] = "疾行海岸",
["Rocktusk Farm"] = "岩猪农场",
["Razorwind Canyon"] = "剃刀峡谷",
["Shrine of the Dormant Flame"] = "休眠之焰祭坛",
["Skull Rock"] = "骷髅石",
["Southfury River"] = "怒水河",
["Burning Blade Coven"] = "燃刃集会所",
["South Seas"] = "南海",

-- ========== 卡利姆多子地名（莫高雷） ==========
["Thunder Bluff"] = "雷霆崖",
["Bloodhoof Village"] = "血蹄村",
["Camp Narache"] = "纳拉其营地",
["Red Cloud Mesa"] = "红云台地",
["The Rolling Plains"] = "起伏平原",
["The Golden Plains"] = "金色平原",
["Ravaged Caravan"] = "被毁的商队",
["Palemane Rock"] = "苍白鬃岩",
["Red Rocks"] = "红石",
["Bael'dun Digsite"] = "巴尔丹挖掘场",
["Winterhoof Water Well"] = "冬蹄水井",
["Great Earth Mother's Beacon"] = "大地之母的灯塔",
["Elder Rise"] = "长者高地",
["Mesa"] = "高地",

-- ========== 卡利姆多子地名（泰达希尔） ==========
["Darnassus"] = "达纳苏斯",
["Darnassus Craftsmen's Terrace"] = "达纳苏斯 工匠区",
["Darnassus Cenarion Enclave"] = "达纳苏斯 塞纳里奥区",
["Darnassus Warrior's Terrace"] = "达纳苏斯 战士区",
["Temple of the Moon"] = "月神殿",
["Dolanaar"] = "多兰纳尔",
["Rut'theran Village"] = "鲁瑟兰村",
["Shadowglen"] = "幽影谷",
["Starbreeze Village"] = "星风村",
["Lake Al'Ameth"] = "阿梅湖",
["Well of Al'Ahwe"] = "阿湖之井",
["Cave of the Frigid Winds"] = "寒风洞穴",
["The Oracle Glade"] = "神谕林",
["Gnarlpine Hold"] = "脊骨堡",
["Ban'ethil Barrow Den"] = "巴奈希尔墓穴",
["Ban'ethil Hollow"] = "巴奈希尔谷地",
["Ruins of Al'Ahn"] = "阿尔恩废墟",
["The Canals"] = "运河",
["The Park"] = "公园",

-- ========== 卡利姆多子地名（黑海岸） ==========
["Auberdine"] = "奥伯丁",
["Bashal'Aran"] = "巴莎兰",
["Remtravel's Excavation"] = "雷姆塔维尔挖掘场",
["Twilight Shore"] = "暮光海岸",
["The Zoram Strand"] = "佐拉姆海岸",
["Cliffspring River"] = "崖泉河",
["Tower of Althalaxx"] = "奥萨拉克斯之塔",
["Mist's Edge"] = "雾之边缘",
["The Master's Glaive"] = "主人的法杖",
["Grove of the Ancients"] = "古树之林",
["Shatterspear Vale"] = "碎矛谷",
["Bittertide Lake"] = "苦潮湖",
["Ban'ethil Beach"] = "巴奈希尔海滩",
["Furien's Post"] = "弗瑞恩的哨岗",
["Sunken Temple of the Moon"] = "沉没的月神殿",
["Mathystra Reliquary"] = "玛希斯特拉圣物箱",
["Howling Vale"] = "嚎风谷",
["Ruins of Mathystra"] = "玛希斯特拉废墟",
["Nighthaven"] = "月光林地",

-- ========== 卡利姆多子地名（贫瘠之地） ==========
["The Crossroads"] = "十字路口",
["Camp Taurajo"] = "陶拉祖营地",
["Ratchet"] = "棘齿城",
["The Wailing Caverns"] = "哀嚎洞穴",
["Agama'gor"] = "阿伽玛戈",
["Bael Modan"] = "巴尔莫丹",
["Blackthorn Ridge"] = "黑刺岭",
["Dreadmist Peak"] = "鬼雾峰",
["Far Watch Post"] = "远望哨岗",
["Lushwater Oasis"] = "甜水绿洲",
["The Sludge Fen"] = "淤泥沼泽",
["The Forgotten Pools"] = "遗忘之池",
["Boulder Lode Mine"] = "巨石矿洞",
["The Dry Hills"] = "干涸山丘",
["Northwatch Hold"] = "北方城堡",
["The Stagnant Oasis"] = "死水绿洲",
["Razorfen Kraul"] = "剃刀沼泽",
["Razorfen Downs"] = "剃刀高地",
["The Shrine of the Dormant Flame"] = "休眠之焰祭坛",
["Thorn Hill"] = "荆棘山",
["The Merchant Coast"] = "商旅海岸",
["Dawnrise Expedition"] = "晨升远征队营地",
["Echo of the Elements"] = "元素回响之地",
["Shimmering Flats"] = "闪光平原",
["The Great Lift"] = "升降梯",
["The Gold Road"] = "黄金之路",
["The Grimtotem Post"] = "恐怖图腾哨岗",
["The Pillar of Heaven"] = "天堂之柱",
["The Screeching Canyon"] = "尖啸峡谷",
["The Tropic"] = "热带",
["The Death's End"] = "死亡之终",
["Mountain of Giants"] = "巨人山",
["The Shuddering Ledge"] = "战栗之地",
["The Grimtotem Compound"] = "恐怖图腾营地",
["The Rustmaul Digsite"] = "锈锤挖掘场",
["The Brambleblade Ravine"] = "荆棘谷",
["The Great Divide"] = "大裂口",

-- ========== 卡利姆多子地名（石爪山脉） ==========
["Sun Rock Retreat"] = "烈日石居",
["Stonetalon Peak"] = "石爪峰",
["The Charred Vale"] = "焦炭谷",
["Mirkfallon Lake"] = "密克弗伦湖",
["Sishir Canyon"] = "西斯尔峡谷",
["The Greatwood Vale"] = "大树谷",
["Webwinder Path"] = "织网者小径",
["Grimtotem Post"] = "恐怖图腾哨岗",
["Blackwolf Camp"] = "黑狼营地",
["Krom'gar Fortress"] = "克罗姆加要塞",
["Battlescar Valley"] = "战痕谷",
["Venture Co. Mine"] = "风险投资公司矿洞",
["Mirkfallon Post"] = "密克弗伦哨岗",
["The Lost Ledge"] = "失落之地",
["Talon Den"] = "爪兽洞穴",
["Windfury Ridge"] = "风怒山脊",
["Windrock Mountain"] = "风岩山",
["Boulder'gor"] = "砾石戈",
["The Screeching Vale"] = "尖啸谷",
["The Wailing Winds"] = "尖啸之风",

-- ========== 卡利姆多子地名（灰谷） ==========
["Astranaar"] = "阿斯特兰纳",
["Splintertree Post"] = "碎木岗哨",
["Zoram'gar Outpost"] = "佐拉姆加前哨站",
["Forest Song"] = "林歌神殿",
["Maestra's Post"] = "迈斯特拉岗哨",
["The Shrine of Aessina"] = "艾森娜神殿",
["Felfire Hill"] = "魔火坡",
["The Ruins of Ordil'Aran"] = "奥迪拉兰废墟",
["Silverwind Refuge"] = "银风避难所",
["Iris Lake"] = "虹光湖",
["Lake Falathim"] = "法拉希姆湖",
["Fallen Sky Lake"] = "陨落天湖",
["Mystral Lake"] = "迈斯特拉湖",
["The Demon Fall Canyon"] = "恶魔陨落峡谷",
["The Morlos'Aran"] = "摩罗萨兰",
["Wardens' Path"] = "守望者小径",
["The Ruins of Stardust"] = "星尘废墟",
["Bough Shadow"] = "树荫谷",
["The Nightmare Vale"] = "噩梦谷",
["Blackfathom Camp"] = "黑暗深渊营地",
["The Veiled Sea"] = "神秘之海",
["The Blackfathom Deeps"] = "黑暗深渊",
["The Temple of Cenarius"] = "塞纳留斯神殿",
["The Emerald Sanctuary"] = "翡翠避难所",
["Duskrise"] = "黄昏崛起",
["The Nightwood"] = "夜色森林",
["The Scythe of Elune"] = "艾露恩之镰",
["The Wolf's Den"] = "狼穴",
["The Grol'dom Farm"] = "格罗多姆农场",

-- ========== 卡利姆多子地名（千针石林） ==========
["Freewind Post"] = "乱风岗",
["Darkcloud Pinnacle"] = "黑云峰",
["Splithoof Crag"] = "裂蹄峭壁",
["Highperch"] = "高栖地",
["Camp E'thok"] = "艾瑟克营地",
["Mirage Raceway"] = "幻象跑道",
["The Western Causeway"] = "西部石桥",
["The Raptor Grounds"] = "迅猛龙之地",
["The Spearhead"] = "矛尖",
["The Needles"] = "针石",
["The Salt Flats"] = "盐滩",
["The Ruins of the Great Lift"] = "升降梯废墟",
["The Splithoof Pass"] = "裂蹄小径",

-- ========== 卡利姆多子地名（凄凉之地） ==========
["Nijel's Point"] = "尼耶尔前哨站",
["Shadowprey Village"] = "暗影猎手村",
["Mannoroc Coven"] = "玛诺洛克集会所",
["Ethel Rethor"] = "埃瑟尔·雷索",
["Valley of Spears"] = "长矛谷",
["Kodo Graveyard"] = "科多兽坟场",
["Gelkis Village"] = "吉尔吉斯村",
["Kolkar Village"] = "科尔卡村",
["Sargeron"] = "萨格隆",
["Raven's Wind"] = "乌鸦风",
["Thunder Axe Fortress"] = "雷斧堡垒",
["The Shimmering Wastes"] = "闪耀荒地",
["The Golden Vale"] = "金色谷",
["The Demon Scar"] = "恶魔之痕",
["The Hammer Fall"] = "锤落之地",
["The Scorched Plain"] = "灼热平原",
["The Lost Village of Dr. Moreau"] = "莫罗博士的失落村庄",
["The Forest of Distraction"] = "迷惑之林",
["The Port of Death"] = "死亡之港",
["The Witch's Garden"] = "女巫花园",
["The Snow Mountain"] = "雪山",
["The Blasted Barrens"] = "毁坏之地",
["The Centaur Plains"] = "半人马平原",
["The Kodo Graveyard"] = "科多兽坟场",
["The Magram Village"] = "玛格拉姆村",
["The Maraudon"] = "玛拉顿",
["The Unbroken Path"] = "未破碎之路",
["The Razorfen"] = "剃刀岭",
["The Temple of Ahn'Qiraj"] = "安其拉神庙",

-- ========== 卡利姆多子地名（尘泥沼泽） ==========
["Theramore Isle"] = "塞拉摩岛",
["Brackenwall Village"] = "蕨墙村",
["Stonemaul Village"] = "石槌村",
["Blackhoof Village"] = "黑蹄村",
["Mudsprocket"] = "泥链镇",
["Alcaz Island"] = "奥卡兹岛",
["Bloodfen Burrow"] = "血沼洞",
["Wyrmbog"] = "龙泥沼",
["The Shady Rest"] = "阴凉之地",
["The Lost Ruins"] = "失落废墟",
["The Quagmire"] = "泥潭",
["The Fang"] = "魔牙",
["The Dustwallow Bay"] = "尘泥海湾",
["The Deep"] = "深渊",
["The Nautical Graveyard"] = "航海墓地",
["The Deadmire"] = "死泥沼泽",
["The Temple of the Damned"] = "诅咒神庙",
["The Shadowed Strand"] = "暗影海岸",
["The Tidal Flat"] = "潮汐滩",
["The Muddy Mire"] = "泥泞之地",
["The Tangled Cave"] = "盘绕洞穴",

-- ========== 卡利姆多子地名（菲拉斯） ==========
["Feathermoon Stronghold"] = "羽月要塞",
["Camp Mojache"] = "莫沙彻营地",
["Dreamer's Rest"] = "梦见之憩",
["Camp Ataya"] = "阿塔亚营地",
["Dire Maul"] = "厄运之槌",
["Isle of Dread"] = "恐惧之岛",
["Feral Scar Vale"] = "菲拉斯疤痕谷",
["Jademir Lake"] = "翡翠湖",
["The Ruins of Isildien"] = "伊希迪恩废墟",
["The Twin Colossals"] = "双子柱石",
["The Lost Temple of Elune"] = "失落的艾露恩神殿",
["The Writhing Deep"] = "痛苦深渊",
["The Savage Thicket"] = "野蛮丛林",
["The Ruins of Constellas"] = "康斯坦拉废墟",
["The Ogres of Feralas"] = "菲拉斯食人魔",
["The Shimmering Sands"] = "闪烁沙地",
["The Wildwind Path"] = "野风小径",
["The Verdantis River"] = "沃丹提斯河",
["The High Wilderness"] = "高等荒野",
["The Forgotten Coast"] = "被遗忘的海岸",
["The Dragon's Tooth"] = "龙牙",
["The Hive'Regal"] = "雷戈虫巢",
["The Hive'Zora"] = "佐拉虫巢",
["The Hive'Ashi"] = "亚什虫巢",
["The Ruins of Ravenwind"] = "鸦风废墟",
["The Valley of the Watchers"] = "守望者之谷",
["The Shadowed Grove"] = "暗影林",
["The Crystal Shore"] = "水晶海岸",
["The Northern Barrens"] = "北贫瘠之地",
["The Southern Barrens"] = "南贫瘠之地",
["The Thousand Needles"] = "千针石林",
["The Desolace"] = "凄凉之地",

-- ========== 卡利姆多子地名（塔纳利斯） ==========
["Gadgetzan"] = "加基森",
["Zul'Farrak"] = "祖尔法拉克",
["The Caverns of Time"] = "时光之穴",
["Abyssal Sands"] = "深渊沙地",
["Broken Pillar"] = "破碎之柱",
["Thistleshrub Valley"] = "蓟皮谷",
["The Dunemaul Compound"] = "沙槌营地",
["The Gaping Chasm"] = "大裂痕",
["The Wastes of Tanaris"] = "塔纳利斯荒地",
["The Noxious Lair"] = "毒牙巢穴",
["The Scorched Vale"] = "焦灼谷",
["The Ruins of Khin'jan"] = "钦让废墟",
["The Forbidden Pass"] = "禁忌之径",
["The Searing Sands"] = "灼热沙地",
["The Lost City of the Tol'vir"] = "托维尔失落之城",
["The Temple of Uldum"] = "奥丹姆神殿",
["The Desert of Tanaris"] = "塔纳利斯沙漠",
["The Southsea Freebooters"] = "南海海盗",
["The Sandfury"] = "沙怒",
["The Scorpid Dunes"] = "蝎子沙丘",
["The Wastewander"] = "废土",
["The Steamwheedle Port"] = "热砂港",
["The Bootlegger's Cove"] = "走私者海湾",
["The Theramore Harbor"] = "塞拉摩港口",

-- ========== 卡利姆多子地名（艾萨拉） ==========
["Talrendis Point"] = "塔伦迪斯营地",
["Valormok"] = "瓦罗莫克",
["The Bay of Storms"] = "风暴海湾",
["Forlorn Ridge"] = "绝望山脊",
["Bitter Reaches"] = "痛苦之地",
["The Ruins of Eldarath"] = "艾萨拉废墟",
["The Horde Camp"] = "部落营地",
["The Shimmering Reef"] = "闪亮珊瑚礁",
["The Weathered Shallows"] = "风蚀浅滩",
["The Whispering Shore"] = "低语海岸",

-- ========== 卡利姆多子地名（费伍德森林） ==========
["Talonbranch Glade"] = "语风林地",
["Bloodvenom Post"] = "血毒岗哨",
["Deadwood Village"] = "死木村",
["Felpaw Village"] = "魔爪村",
["Bloodvenom Falls"] = "血毒瀑布",
["The Shrine of the Moon"] = "月之神殿",
["The Shadow Hold"] = "暗影堡",
["The Felwood Forest"] = "费伍德森林",
["The Irontree Woods"] = "铁木森林",
["The Jaedenar"] = "加德纳尔",
["The Sorrow Hill"] = "悔恨岭",

-- ========== 卡利姆多子地名（安戈洛环形山） ==========
["Marshal's Refuge"] = "马绍尔营地",
["Fire Plume Ridge"] = "火羽山",
["Golakka Hot Springs"] = "格拉卡温泉",
["Lakkari Tar Pits"] = "拉卡利油沼",
["Fungal Rock"] = "真菌岩",
["Ironstone Plateau"] = "铁石高原",
["The Slithering Scar"] = "蛇痕谷",
["The Marshlands"] = "沼泽地",
["The Terror Run"] = "恐怖小径",
["The Northern Pylon"] = "北水晶塔",
["The Western Pylon"] = "西水晶塔",
["The Eastern Pylon"] = "东水晶塔",
["The Un'Goro Crater"] = "安戈洛环形山",

-- ========== 卡利姆多子地名（冬泉谷） ==========
["Everlook"] = "永望镇",
["Frostsaber Rock"] = "霜刃石",
["Winterfall Village"] = "冬泉村",
["Frostfire Springs"] = "霜火泉",
["Winterfall Post"] = "冬泉哨岗",
["Starfall Village"] = "坠星村",
["The Timbermaw Hold"] = "木喉要塞",
["Darkwhisper Gorge"] = "暗语峡谷",
["The Ruins of Winterspring"] = "冬泉谷废墟",
["The Frostsaber Den"] = "霜刃巢穴",
["The Frozen Lake"] = "冰封湖",
["The Snowblind Hills"] = "雪盲丘陵",
["The Winterspring Grove"] = "冬泉林",
["The Felwood"] = "费伍德森林",
["The Azshara"] = "艾萨拉",
["The Winterspring"] = "冬泉谷",
["The Frostsaber"] = "霜刃豹",
["The Winterfall"] = "冬泉熊怪",

-- ========== 卡利姆多子地名（月光林地） ==========
["Lake Elune'ara"] = "艾露恩湖",
["Shrine of Remulos"] = "雷姆洛斯神殿",
["Stormrage Barrow Dens"] = "怒风兽穴",
["The Emerald Dreamway"] = "翡翠梦境之路",
["The Moonglade"] = "月光林地",
["The Nighthaven"] = "夜港",
["The Moonglade's Edge"] = "月光林地边缘",
["The North Shore"] = "北岸",
["The South Shore"] = "南岸",

-- ========== 卡利姆多子地名（希利苏斯） ==========
["Cenarion Hold"] = "塞纳里奥要塞",
["Valor's Rest"] = "勇气之憩",
["Staghelm Point"] = "鹿盔岗哨",
["Southwind Village"] = "南风村",
["The Crystal Vale"] = "水晶谷",
["Twilight Base Camp"] = "暮光营地",
["Bronzebeard Encampment"] = "铜须营地",
["The Scarab Wall"] = "甲虫之墙",
["Hive'Ashi"] = "亚什虫巢",
["Hive'Zora"] = "佐拉虫巢",
["Hive'Regal"] = "雷戈虫巢",
["Ahn'Qiraj"] = "安其拉",
["The Ruins of Ahn'Qiraj"] = "安其拉废墟",
["The Scarlet Watch"] = "血色守望",
["The Dustwind Pillar"] = "尘风柱",
["The Hive'Ashi Sands"] = "亚什虫巢沙地",
["The Hive'Zora Sands"] = "佐拉虫巢沙地",
["The Hive'Regal Sands"] = "雷戈虫巢沙地",
["The Silithus"] = "希利苏斯",

-- ========== 卡利姆多子地名（秘蓝岛） ==========
["Ammen Vale"] = "安曼谷",
["Azure Watch"] = "蓝风守望",
["Odesyus' Landing"] = "奥德修斯码头",
["The Exodar"] = "埃索达",
["The Crystal Hall"] = "水晶大厅",
["The Vault of Lights"] = "光之穹殿",
["The Seat of the Naaru"] = "纳鲁之座",

-- ========== 卡利姆多子地名（秘血岛） ==========
["Blood Watch"] = "血望堡",
["The Ruins of Shadowmoon"] = "影月废墟",
["The Vault of Shadows"] = "暗影穹殿",

-- ========== 东部王国子地名（艾尔文森林） ==========
["Stormwind City"] = "暴风城",
["Stormwind Keep"] = "暴风城要塞",
["Trade District"] = "贸易区",
["Cathedral Square"] = "大教堂广场",
["Mage Quarter"] = "法师区",
["Dwarven District"] = "矮人区",
["Old Town"] = "旧城区",
["Goldshire"] = "闪金镇",
["Northshire"] = "北郡",
["Northshire Abbey"] = "北郡修道院",
["Eastvale Logging Camp"] = "东谷伐木场",
["Westbrook Garrison"] = "西泉要塞",
["The Stonefield Farm"] = "斯通菲尔德农场",
["Maclure Vineyards"] = "麦克拉伦葡萄园",
["Jasperlode Mine"] = "玉石矿洞",
["Echo Ridge Mine"] = "回音山矿井",
["Forest's Edge"] = "林边空地",
["Ridgepoint Tower"] = "山脊点塔",
["Tower of Azora"] = "阿祖拉之塔",

-- ========== 东部王国子地名（西部荒野） ==========
["Sentinel Hill"] = "哨兵岭",
["Moonbrook"] = "月溪镇",
["The Deadmines"] = "死亡矿井",
["Saldean's Farm"] = "萨尔丁农场",
["The Jansen Stead"] = "詹森农场",
["The Dagger Hills"] = "匕首山",
["Demont's Place"] = "迪蒙特营地",
["Alexston Farmstead"] = "亚历克斯顿农场",
["Furlbrow's Pumpkin Farm"] = "弗尔布鲁南瓜田",
["Gold Coast Quarry"] = "金海岸矿坑",

-- ========== 东部王国子地名（暮色森林） ==========
["Darkshire"] = "夜色镇",
["Raven Hill"] = "乌鸦岭",
["Raven Hill Cemetery"] = "乌鸦岭墓地",
["Tranquil Gardens Cemetery"] = "静谧花园墓场",
["Beggar's Haunt"] = "乞丐鬼屋",
["Haunted Manor"] = "荒弃鬼屋",
["Vul'Gol Ogre Mound"] = "沃古尔食人魔山",
["Manor Mistmantle"] = "密斯特曼托庄园",
["Yorgen Farmstead"] = "约根农场",
["Rotting Orchard"] = "烂果园",
["Sunnyglade"] = "阳光树林",
["Dawnwood"] = "黎明森林",
["Hushed Bank"] = "寂静河岸",
["Dusky Bank"] = "暗色河滩",
["Foulweald Den"] = "腐草农场",
["Greenwarden's Grove"] = "青卫丛林",
["Terrorweb Tunnel"] = "恐蛛隧道",
["Abercrombie's Shack"] = "阿伯克龙比的小屋",
["Addle's Stead"] = "阿德尔农场",
["Violet Tower"] = "紫罗兰塔",

-- ========== 东部王国子地名（赤脊山） ==========
["Lakeshire"] = "湖畔镇",
["Stonewatch Keep"] = "石堡要塞",
["Stonewatch Falls"] = "石堡瀑布",
["Render's Camp"] = "撕裂者营地",
["Render's Valley"] = "撕裂者山谷",
["Render's Rock"] = "撕裂者岩石",
["Lake Everstill"] = "止水湖",
["Galardell Valley"] = "加拉德尔山谷",
["Shalewind Canyon"] = "石风峡谷",
["Three Corners"] = "三角路口",
["The Algaz Station"] = "阿尔加兹站",

-- ========== 东部王国子地名（逆风小径） ==========
["Karazhan"] = "卡拉赞",
["The Master's Cellar"] = "主人地窖",
["Servants' Quarters"] = "仆役宿舍",
["The Guest Chambers"] = "宾客客房",
["The Menagerie"] = "动物园",
["The Library"] = "图书馆",
["The Observatory"] = "天文台",
["The Rookery"] = "乌鸦巢",
["The Broken Stair"] = "断裂阶梯",
["Gradener's Perch"] = "花匠之栖",

-- ========== 东部王国子地名（悲伤沼泽） ==========
["Stonard"] = "斯通纳德",
["Temple of Atal'Hakkar"] = "阿塔哈卡神庙",
["The Sunken Temple"] = "沉没的神庙",
["Misty Reed Strand"] = "芦苇海滩",
["Misty Reed Post"] = "芦苇岗哨",
["Misty Reed Fen"] = "芦苇沼泽",
["Pool of Tears"] = "泪水之池",
["Fallow Sanctuary"] = "荒原圣所",
["The Harborage"] = "避难所",
["Garren's Haunt"] = "加伦鬼屋",
["Itharius's Cave"] = "伊萨里奥斯的洞穴",

-- ========== 东部王国子地名（诅咒之地） ==========
["The Dark Portal"] = "黑暗之门",
["Nethergarde Keep"] = "守望堡",
["Serpent's Coil"] = "蛇之卷曲",
["The Tainted Scar"] = "污痕之地",
["Dreadmaul Hold"] = "巨槌要塞",
["Red Stone Run"] = "红石小径",
["Shadow Hold"] = "暗影堡",
["Altar of Storms"] = "风暴祭坛",
["The Throttle"] = "怨石",
["The Red Reaches"] = "红色之地",
["Nethergarde Mining Operation"] = "守望堡采矿场",

-- ========== 东部王国子地名（荆棘谷） ==========
["Booty Bay"] = "藏宝海湾",
["Grom'gol Base Camp"] = "格罗姆高营地",
["Gurubashi Arena"] = "古拉巴什竞技场",
["Zul'Gurub"] = "祖尔格拉布",
["The Ruins of Zul'Gurub"] = "祖尔格拉布废墟",
["The Gurubashi Empire"] = "古拉巴什帝国",
["Nesingwary's Expedition"] = "奈辛瓦里远征队营地",
["The Cape of Stranglethorn"] = "荆棘谷海角",
["Jungle of Stranglethorn"] = "荆棘谷丛林",
["The Great Waterfall"] = "大瀑布",
["Mosh'Ogg Ogre Mound"] = "摩什奥格食人魔山",
["Kal'ai Ruins"] = "卡莱废墟",
["Zul'Mamwe"] = "祖尔玛维",
["Bal'lal Ruins"] = "巴拉尔废墟",
["Venture Co. Base Camp"] = "风险投资公司营地",
["Kurzen's Compound"] = "库尔森营地",
["Wild Shore"] = "蛮荒海岸",
["The Savage Coast"] = "野蛮海岸",
["Bloodmoon Isle"] = "血月岛",

-- ========== 东部王国子地名（燃烧平原） ==========
["Morgan's Vigil"] = "摩根的哨岗",
["Blackrock Mountain"] = "黑石山",
["Blackrock Stronghold"] = "黑石要塞",
["Blackrock Pass"] = "黑石小径",
["Dreadmaul Rock"] = "巨槌石",
["Flame Crest"] = "烈焰峰",
["Flamecrest"] = "烈焰锋",
["The Pillar of Ash"] = "灰烬之柱",
["The Ruins of Thaurissan"] = "索瑞森废墟",
["Giant's Run"] = "巨槌石",
["Firegut Furnace"] = "火腹熔炉",
["Skull's Bend"] = "颅骨密径",
["The Vault"] = "地库",
["Terror Wing Path"] = "恐怖翼径",
["Blackrock Spire"] = "黑石塔",
["Blackrock Depths"] = "黑石深渊",
["Burning Steppes"] = "燃烧平原",
["Lake Thaurissan"] = "索瑞森湖",

-- ========== 东部王国子地名（灼热峡谷） ==========
["Thorium Point"] = "瑟银哨点",
["Steamwhistle Gorge"] = "汽笛峡谷",
["The Cauldron"] = "大坩埚",
["Cauldron's Wastes"] = "坩埚荒地",
["Grimesilt Dig Site"] = "格里米挖泥场",
["The Slag Pit"] = "矿渣坑",
["Observatory"] = "天文台",
["The Dustbowl"] = "尘盆",
["The Gateway to Molten Core"] = "熔火之心入口",

-- ========== 东部王国子地名（荒芜之地） ==========
["Kargath"] = "卡加斯",
["Angor Fortress"] = "安戈洛堡垒",
["Camp Cagg"] = "卡格营地",
["The Badlands"] = "荒芜之地",
["The Dustbelch Mountains"] = "尘怒山脉",
["The Drag"] = "拖车区",
["Burning Blade Quarry"] = "燃刃矿场",
["Lethlor Ravine"] = "莱斯罗尔峡谷",
["Apocryphan's Rest"] = "阿波克里凡的休息地",
["The Temple of Bone"] = "白骨神殿",

-- ========== 东部王国子地名（丹莫罗） ==========
["Ironforge"] = "铁炉堡",
["Kharanos"] = "卡拉诺斯",
["Gol'Bolar Quarry"] = "古博拉采掘场",
["Anvilmar"] = "安威玛尔",
["Coldridge Valley"] = "寒脊山谷",
["Brewnall Village"] = "酿酿村",
["Brewery"] = "酿酒厂",
["Thunderbrew Distillery"] = "雷酒酿制厂",
["The Tundrid Hills"] = "冻山",
["The Grizzled Den"] = "灰爪巢穴",
["Shimmer Ridge"] = "微光岭",
["Mistmantle's Revenge"] = "雾纹复仇",
["Amberstill Ranch"] = "琥珀still牧场",
["Icesoft Cavern"] = "软冰洞穴",
["Ironband's Excavation Site"] = "铁环挖掘场",
["The Algaz Gate"] = "阿尔加兹之门",
["The Great Forge"] = "大熔炉",
["The High Seat"] = "王座大厅",
["The Mystic Ward"] = "秘法区",
["The Commons"] = "平民区",
["Military Ward"] = "军事区",
["Tinker Town"] = "侏儒区",

-- ========== 东部王国子地名（洛克莫丹） ==========
["Thelsamar"] = "塞尔萨玛",
["Loch Modan Lake"] = "洛克湖",
["The Loch"] = "洛克",
["The Dam"] = "大坝",
["Dun Algaz"] = "丹奥加兹",
["The Stonewrought Dam"] = "石坝大坝",
["Stonewrought Pass"] = "石坝小径",
["Ironband's Excavation"] = "铁环挖掘场",
["The Farstrider Lodge"] = "远行旅社",
["Mossy Steps"] = "苔阶",
["Thelgen Rock"] = "塞尔根岩",
["Valley of Kings"] = "国王谷",
["Tunnel of Lamentation"] = "悲鸣隧道",
["Stonesplinter Valley"] = "碎石谷",
["Moonkissed Meadow"] = "月吻草地",
["Ironbeard's Tomb"] = "铁须之墓",

-- ========== 东部王国子地名（湿地） ==========
["Menethil Harbor"] = "米奈希尔港",
["Dragonmaw Gates"] = "龙喉之门",
["The Thandol Span"] = "萨多尔大桥",
["Whelp's Wary"] = "雏龙栖息地",
["Mosshide Fen"] = "苔藓沼泽",
["The Green Belt"] = "绿带",
["The Ashen Coast"] = "灰烬海岸",
["Baradin Bay"] = "巴拉尔湾",
["The Forbidding Sea"] = "禁海",
["Raptor Ridge"] = "迅猛龙岭",
["Misty Shore"] = "迷雾海岸",
["Bluegill Woods"] = "蓝鳃树林",
["Whelp's Escape"] = "幼龙逃脱地",
["Direforge Hill"] = "恐锤山",

-- ========== 东部王国子地名（阿拉希高地） ==========
["Refuge Pointe"] = "避难谷地",
["Hammerfall"] = "落锤镇",
["Stromgarde Keep"] = "激流堡",
["Go'Shek Farm"] = "格沙克农场",
["Circle of West Binding"] = "西束缚法阵",
["Circle of Inner Binding"] = "内束缚法阵",
["Northfold Manor"] = "北叠庄园",
["The Altar of Storms"] = "风暴祭坛",
["Boulderfist Hall"] = "石拳大厅",
["Witherbark Village"] = "枯木村",
["Drywhisker Gorge"] = "干须峡谷",
["Stromgarde"] = "激流堡",
["The Hidden Lair"] = "隐秘巢穴",
["The Drowned Reef"] = "沉没暗礁",

-- ========== 东部王国子地名（提瑞斯法林地） ==========
["Undercity"] = "幽暗城",
["Brill"] = "布瑞尔",
["Deathknell"] = "丧钟镇",
["Scarlet Monastery"] = "血色修道院",
["Faol's Rest"] = "法奥之墓",
["Agamand Mills"] = "阿加曼德磨坊",
["Solliden Farmstead"] = "索利丹农场",
["Gallows' End"] = "绞刑场",
["The Bulwark"] = "壁垒",
["Calston Estate"] = "卡尔斯顿庄园",
["The Bloody Fields"] = "血色之地",
["The Sludge Fields"] = "污泥之地",
["The Sewers"] = "下水道",
["The Royal Quarter"] = "皇家区",
["The Apothecarium"] = "炼金房",
["The War Quarter"] = "战争区",
["The Magic Quarter"] = "魔法区",
["The Ruins of Lordaeron"] = "洛丹伦废墟",

-- ========== 东部王国子地名（银松森林） ==========
["The Sepulcher"] = "瑟伯切尔",
["Pyrewood Village"] = "焚木村",
["Ambermill"] = "安博米尔",
["Shadowfang Keep"] = "影牙城堡",
["Beren's Peril"] = "贝伦的危机",
["The Ivar Patch"] = "伊瓦湿地",
["The Shining Strand"] = "闪光滩",
["The Greymane Wall"] = "格雷迈恩之墙",
["Valgan's Field"] = "瓦尔甘田野",
["The Dragon's Tail"] = "龙尾",
["The Rift"] = "裂口",
["Malden's Orchard"] = "马尔登果园",
["The Decrepit Ferry"] = "破败原野",
["Boren's Lair"] = "博伦的巢穴",
["Elim's Mine"] = "埃利姆矿洞",
["The Skittering Dark"] = "蜘蛛洞穴",
["Shadowfang Hold"] = "影牙要塞",

-- ========== 东部王国子地名（希尔斯布莱德丘陵） ==========
["Tarren Mill"] = "塔伦米尔",
["Southshore"] = "南海镇",
["Durnholde Keep"] = "敦霍尔德城堡",
["Hillsbrad Fields"] = "希尔斯布莱德农田",
["Azurelode Mine"] = "碧玉矿洞",
["Ravenholdt Manor"] = "拉文霍德庄园",
["Strahnbrad"] = "斯坦恩布莱德",
["The Headlands"] = "岬角",
["Nethander Stead"] = "内森德农场",
["Northridge"] = "北脊",
["Stonebarb Canyon"] = "石刺峡谷",
["Tower of Arathor"] = "阿拉索之塔",
["The Uplands"] = "高地",
["The Foothills"] = "丘陵地带",
["Lordamere Lake"] = "洛丹米尔湖",
["The Ruins of Southshore"] = "南海镇废墟",

-- ========== 东部王国子地名（奥特兰克山脉） ==========
["Alterac Valley"] = "奥特兰克山谷",
["Alterac City"] = "奥特兰克城",
["Ruins of Alterac"] = "奥特兰克废墟",
["Crushridge"] = "碎石岭",
["Sofera's Naze"] = "索菲亚高地",
["Gallow's Place"] = "绞刑场",
["Dalaran"] = "达拉然",
["Dalaran Crater"] = "达拉然陨坑",
["The Darrowmere Lake"] = "达罗米尔湖",
["Darrowmere Lake"] = "达罗米尔湖",

-- ========== 东部王国子地名（辛特兰） ==========
["Aerie Peak"] = "鹰巢山",
["Revantusk Village"] = "恶齿村",
["Jintha'Alor"] = "辛萨罗",
["Seradane"] = "瑟拉丹",
["Shadra'Alor"] = "沙德拉洛",
["Quel'Danil Lodge"] = "奎尔丹尼旅社",
["The Overlook Cliffs"] = "俯瞰悬崖",
["The Creeping Moss"] = "蔓延苔藓",
["Silver Stream Mine"] = "银溪矿洞",
["The Ruins of Zul'Mamwe"] = "祖尔玛维废墟",

-- ========== 东部王国子地名（西瘟疫之地） ==========
["Chillwind Camp"] = "寒风营地",
["Andorhal"] = "安多哈尔",
["Sorrow Hill"] = "悔恨岭",
["The Writhing Haunt"] = "痛苦鬼屋",
["The Weeping Cave"] = "哭泣洞穴",
["Felstone Field"] = "费尔斯通农场",
["Dalson's Tears"] = "达尔松之泪",
["Hearthglen"] = "壁炉谷",
["The Ruins of Andorhal"] = "安多哈尔废墟",
["Gahrron's Withering"] = "加隆的凋零地",
["The Noxious Glade"] = "毒疫之地",
["The Marris Stead"] = "玛瑞斯农场",

-- ========== 东部王国子地名（东瘟疫之地） ==========
["Light's Hope Chapel"] = "圣光之愿礼拜堂",
["Stratholme"] = "斯坦索姆",
["The Undercroft"] = "地穴",
["Crown Guard Tower"] = "皇冠卫塔",
["Eastwall Tower"] = "东墙哨塔",
["Northpass Tower"] = "北关哨塔",
["Tyr's Hand"] = "提尔之手",
["Darrowshire"] = "达隆郡",
["Corin's Crossing"] = "考林路口",
["The Pestilence Scar"] = "瘟疫之痕",
["Zul'Mashar"] = "祖玛沙尔",
["Blackwood Lake"] = "黑木湖",
["The Fungal Vale"] = "真菌谷",
["The Ruins of Stratholme"] = "斯坦索姆废墟",
["The Carrion Fields"] = "腐肉之地",
["The Scourgeholme"] = "天灾大殿",
["The Thondroril River"] = "索多里尔河",
["The Plaguewood"] = "瘟疫森林",

-- ========== 东部王国子地名（永歌森林） ==========
["Silvermoon City"] = "银月城",
["Sunspire"] = "太阳之尖",
["Falconwing Square"] = "鹰翼广场",
["The Bazaar"] = "集市",
["The Royal Exchange"] = "皇家交易所",
["Murder Row"] = "谋杀巷",
["Farstrider Square"] = "远行者广场",
["Sunfury Spire"] = "日怒尖塔",
["The Golden Strand"] = "金色沙滩",
["Fairbreeze Village"] = "晴风村",
["Rogues' Quarter"] = "盗贼区",
["Scryer's Square"] = "占卜者广场",
["Stillwhisper Pond"] = "静语池塘",
["The Dead Scar"] = "死亡之痕",
["Zeb'Watha"] = "塞布瓦萨",
["Suncrown Village"] = "日冠村",
["Azurebreeze Coast"] = "碧风海岸",
["The Living Forest"] = "生命森林",
["Goldenbough Pass"] = "金枝小径",
["Elrendar Falls"] = "艾伦达尔瀑布",
["Elrendar Lake"] = "艾伦达尔湖",
["North Sanctum"] = "北部圣殿",
["East Sanctum"] = "东部圣殿",
["West Sanctum"] = "西部圣殿",
["Dath'Remar Hall"] = "达斯雷玛大殿",
["Dath'Remar Square"] = "达斯雷玛广场",
["Dath'Remar Tower"] = "达斯雷玛之塔",
["Falthrien Academy"] = "法瑟林学院",
["Runestone Solliden"] = "索利丹符文石",
["Saltheril's Haven"] = "萨尔瑟瑞尔的避风港",
["Tor'Watha"] = "托尔瓦萨",

-- ========== 东部王国子地名（幽魂之地） ==========
["Tranquillien"] = "塔奎林",
["Zul'Aman"] = "祖阿曼",
["Deatholme"] = "戴索姆",
["Windrunner Village"] = "风行者村",
["Windrunner Spire"] = "风行者尖塔",
["The Sanctum of the Sun"] = "太阳圣所",
["The Sanctum of the Moon"] = "月亮圣所",
["The Duskwither Grounds"] = "暮光之地",
["The Cleft"] = "裂隙",
["Amani Pass"] = "阿曼尼通道",
["The Weeping Terrace"] = "哭泣台地",
["Raven's Wood"] = "鸦木",
["Tranquil Shore"] = "宁静海岸",
["The Shadow Vault"] = "暗影地窖",
["The Underlight Mines"] = "幽光矿洞",
["Hatchet Hills"] = "战斧山",

-- ========== 东部王国子地名（吉尔尼斯） ==========
["Gilneas City"] = "吉尔尼斯城",
["The Light's Dawn Cathedral"] = "晨曦大教堂",
["Alpine Way"] = "高山之路",
["The Lost Sycamore"] = "迷失之枫",
["The Northern Wall"] = "北墙",
["The Southern Wall"] = "南墙",
["The Eastern Wall"] = "东墙",
["The Western Wall"] = "西墙",
["The Docks"] = "码头",
["The City Square"] = "城市广场",
["The Cathedral Quarter"] = "大教堂区",
["The Military Quarter"] = "军事区",
["The Merchant Quarter"] = "商业区",
["Emberstone Mine"] = "余烬矿洞",
}

-- ========== NPC与怪物字典 ==========
TDL_NPCDict = {
-- 原有条目
["Defias Bodyguard"] = "迪菲亚保镖",
["Mushgog"] = "穆什戈格",
["Warlord Krom'zar"] = "督军克罗姆扎",
["Deepmoss Matriarch"] = "深苔蛛母",
["Galak Assassin"] = "加拉克刺客",
["Great Father Arctikus"] = "阿克提库斯",
["Lady Moongazer"] = "月爪夫人",
["Stone Fury"] = "石怒地元素",
["Sunscale Screecher"] = "日鳞尖叫者",
["Dark Iron Dwarf"] = "黑铁矮人",
["Lord Vash'arj"] = "瓦什尔领主",
["Defias Pillager"] = "迪菲亚抢劫者",

-- 常见单字及易误判野怪白名单
["Bloodhound"] = "血犬",
["Gargoyle"] = "石像怪",
["Slime"] = "软泥怪",
["Wolf"] = "野狼",
["Bear"] = "熊",
["Spider"] = "蜘蛛",
["Scorpid"] = "蝎子",
["Crocolisk"] = "鳄鱼",
["Raptor"] = "迅猛龙",
["Troll"] = "巨魔",
["Ogre"] = "食人魔",

-- 漏网的稀有及经典野怪
["Kodo Matriarch"] = "科多兽群母",
["Deepmurk Warrior"] = "深渊泥沼战士",
["Stonesplinter Shaman"] = "碎石萨满祭司",
["Venture Co. Drudger"] = "风险投资公司苦工",
["Rockjaw Bonesnapper"] = "石颚断骨者",
["Humar the Pridelord"] = "狮王修玛",

-- 暮色森林及赤脊山野怪系列
["Nightbane Dark Runner"] = "夜行暗影跑者",
["Nightbane Shadow Weaver"] = "夜行影织者",
["Nightbane Vile Fang"] = "夜行邪牙狼人",
["Nightbane Worgen"] = "夜行狼人",
["Shadowhide Slayer"] = "暗影皮杀手",
["Shadowhide Assassin"] = "暗影皮刺客",
["Shadowhide Brute"] = "暗影皮蛮兵",

-- ========== 原版副本怪物 ==========
-- 死亡矿井
["Mr. Smite"] = "拉克佐",
["Edwin VanCleef"] = "艾德温·范克里夫",
["Captain Greenskin"] = "绿皮队长",
["Cookie"] = "厨师饼",
["Gilnid"] = "剪力船工",
["Sneed"] = "撕心狼",
["Defias Overseer"] = "迪菲亚监工",
["Defias Fire Mage"] = "迪菲亚烈焰法师",
["Defias Highwayman"] = "迪菲亚路霸",
["Defias Miner"] = "迪菲亚矿工",
["Defias Traitor"] = "迪菲亚叛徒",
-- 影牙城堡
["Arugal"] = "阿鲁高",
["Lord Walden"] = "狼王南杜斯",
["Archmage Arugal"] = "大法师灰爪",
["Odo the Blindwatcher"] = "奥杜",
["Fenrus the Devourer"] = "芬鲁斯",
["Deathsworn Captain"] = "小怪斯普林特",
["Shadowfang Dreadmage"] = "影牙恐惧法师",
["Shadowfang Shadowwalker"] = "影牙暗影行者",
["Shadowfang Guard"] = "影牙守卫",
["Shadowfang Worgen"] = "影牙狼人",
-- 哀嚎洞穴
["Dreamscythe"] = "迦玛兰",
["Venomous Skitterer"] = "毒液撕咬者",
["Fangor the Devourer"] = "尖牙德鲁伊",
["Anacondra"] = "安娜科德拉",
["Cobrahn"] = "考布莱恩",
["Pythas"] = "皮萨斯",
["Dreamstalker"] = "梦境行者",
["Dream Wanderer"] = "梦游者",
["Corrupted Beast"] = "腐化野兽",
["Corrupted Elemental"] = "腐化元素",
["Venomous Murloc"] = "毒液蜥蜴人",
-- 血色修道院
["Bloodmage Thalnos"] = "血法师萨尔诺斯",
["Scarlet Executioner"] = "血色刽子手",
["Scarlet Priest"] = "血色祭司",
["Scarlet Initiate"] = "血色新兵",
["Scarlet Soldier"] = "血色战士",
["Scarlet Zealot"] = "血色狂热者",
["Houndmaster Loksey"] = "驯犬者洛克希",
["Arcanist Doan"] = "血色大法师韦斯特",
["Scarlet Summoner"] = "血色召唤师",
["Scarlet Mage"] = "血色法师",
["Scarlet Acolyte"] = "血色学徒",
["Scarlet Librarian"] = "血色图书管理员",
["Commander Malor"] = "血色指挥官马杜克",
["Scarlet Guardian"] = "血色卫士",
["Scarlet Protector"] = "血色护法",
["Scarlet Grunt"] = "血色士兵",
["Scarlet Cavalier"] = "血色骑士",
["High Inquisitor Whitemane"] = "高阶牧师惠斯勒",
["Scarlet Warrior Hermann"] = "血色十字军战士赫尔曼",
["Scarlet Fanatic"] = "血色狂热者",
["Scarlet Cathedral Guard"] = "血色教堂卫士",
["Scarlet Monk"] = "血色僧侣",
["Scarlet Bodyguard"] = "血色保镖",
-- 剃刀沼泽
["Agathelos the Raging"] = "阿格诺",
["Blind Hunter"] = "盲眼猎手",
["Charlga Razorflank"] = "卡尔加·刺肋",
["Lord Ramtusk"] = "主宰拉姆塔斯",
["Razorfen Spearhide"] = "拉戈斯诺特",
["Razorfen Oracle"] = "剃刀沼泽预言者",
["Razorfen Defender"] = "剃刀沼泽护卫",
["Razorfen Warrior"] = "剃刀沼泽战士",
["Razorfen Quilboar"] = "剃刀沼泽野猪",
-- 剃刀高地
["Tuten'kash"] = "图特卡什",
["Mordresh Fire Eye"] = "莫德雷斯",
["Glutton"] = "暴食者",
["Amnennar the Coldbringer"] = "寒冰之王安多哈尔",
["Razorfen Necromancer"] = "剃刀高地亡灵法师",
["Razorfen Guard"] = "剃刀高地卫兵",
["Razorfen Skeleton"] = "剃刀高地骷髅",
-- 奥达曼
["Archaedas"] = "阿扎达斯",
["Ironaya"] = "艾隆纳亚",
["Ancient Stone Keeper"] = "上古巨人",
["Galgann Firehammer"] = "格里哈斯特",
["Revelosh"] = "鲁维罗什",
["Olaf"] = "奥拉夫",
["Baelog"] = "巴尔洛戈",
["Eric"] = "艾瑞克",
["Uldaman Stone Lord"] = "奥达曼石领",
["Uldaman Rock Breaker"] = "奥达曼碎石者",
["Uldaman Dwarf"] = "奥达曼矮人",
["Uldaman Stone Golem"] = "奥达曼石像",
-- 诺莫瑞根
["Mekgineer Thermaplugg"] = "机械师瑟玛普拉格",
["Electrocutioner 6000"] = "电刑器6000型",
["Grubbis"] = "格鲁比斯",
["Viscous Fallout"] = "粘性辐射尘",
["Crowd Pummeler 9-60"] = "群体打击者9-60",
["Dark Iron Ambassador"] = "黑暗守卫",
["Gnomeregan Security"] = "诺莫瑞根警卫",
["Gnomeregan Engineer"] = "诺莫瑞根工程师",
["Gnomeregan Robot"] = "诺莫瑞根机器人",
["Gnomeregan Trogg"] = "诺莫瑞根穴居人",
-- 玛拉顿
["Noxxion"] = "诺克赛恩",
["Princess Theradras"] = "普罗达摩尔",
["Attumen the Huntsman"] = "阿塔拉利恩",
["Gotik the Harvester"] = "收割者戈提克",
["Vilepetal"] = "维利塔恩",
["Landslide"] = "兰斯利德",
["Celebras the Cursed"] = "被诅咒的塞雷布拉斯",
["Razorlash"] = "锐刺鞭笞者",
["Rotgrip"] = "洛特格里普",
["Centaur Warrior"] = "穴居人战士",
["Elemental"] = "元素生物",
["Maraudon Lasher"] = "玛拉顿鞭笞者",
["Maraudon Corruptor"] = "玛拉顿腐化者",
-- 祖尔法拉克
["Gahz'rrilla"] = "加兹瑞拉",
["Antu'sul"] = "安图苏尔",
["Witch Doctor Zum'rah"] = "巫医祖穆拉恩",
["Nekrum Gutchewer"] = "耐克鲁姆",
["Sergeant Bly"] = "布莱中士",
["Shadowpriest Sezz'ziz"] = "暗影猎手沃什加斯",
["Hydromancer Velratha"] = "海多斯伯恩",
["Theka the Martyr"] = "多色守护者",
["Zul Farrak Executioner"] = "祖尔法拉克刽子手",
["Zul Farrak Witch Doctor"] = "祖尔法拉克巫医",
["Zul Farrak Warrior"] = "祖尔法拉克战士",
["Zul Farrak Ogre"] = "祖尔法拉克食人魔",
-- 神庙
["Shade of Eranikus"] = "伊兰尼库斯之影",
["Hazzas"] = "哈卡的化身",
["Ogom the Wretched"] = "奥戈姆",
["Jammal'an the Prophet"] = "预言者伽玛兰",
["Morphaz"] = "洛考尔",
["Atal'alarion"] = "阿塔拉利恩",
["Temple Dragontamer"] = "神庙龙人",
["Temple Guardian"] = "神庙守护者",
["Temple Troll"] = "神庙巨魔",
["Temple Serpent"] = "神庙蛇人",
-- 黑石深渊
["Emperor Thaurissan"] = "索瑞森大帝",
["Magmus"] = "玛格姆斯",
["Interrogator Gerstahn"] = "审讯官格斯塔恩",
["Houndmaster Grebmar"] = "驯犬者格雷布玛尔",
["Lord Roccor"] = "洛考尔",
["Ok'thor the Breaker"] = "破坏者奥科索尔",
["Warden Stilgiss"] = "典狱官斯迪尔基斯",
["Fineous Darkvire"] = "弗诺斯·达克维尔",
["Ambassador Flamelash"] = "弗莱拉斯大使",
["Argelmach"] = "傀儡统帅阿格曼奇",
["Bael'Gar"] = "贝尔加",
["Phalanx"] = "法拉克斯",
["General Angerforge"] = "怒炉将军",
["Guard Mol'dar"] = "卫兵多尔夫",
["Plugger Spazzring"] = "卫兵普拉格",
["Marshal Windsor"] = "温德索尔元帅",
["Iron Guard"] = "铁怒元帅",
["High Interrogator Gerstahn"] = "高阶女祭司吉尔娜",
["Ribbly Screwspigot"] = "雷布里·斯库比格特",
["Dark Iron Guard"] = "黑铁守卫",
["Dark Iron Mage"] = "黑铁法师",
["Dark Iron Warrior"] = "黑铁战士",
["Dark Iron Miner"] = "黑铁矿工",
-- 厄运之槌
["Prince Tortheldrin"] = "托塞德林王子",
["Immol'thar"] = "伊莫塔尔",
["Pusillin"] = "观察者克鲁什",
["Zevrim Thornhoof"] = "米兹勒",
["Alzzin the Wildshaper"] = "奥兹恩",
["King Gordok"] = "戈多克大王",
["Kromcrush"] = "克罗卡斯",
["Gordok Might"] = "戈多克领主",
["Tendris Warpwood"] = "特迪斯·扭木",
["Hydrospawn"] = "海多斯博恩",
["Dire Maul Undead"] = "厄运之槌亡灵",
["Dire Maul Demon"] = "厄运之槌恶魔",
["Dire Maul Satyr"] = "厄运之槌萨特",
["Dire Maul Treant"] = "厄运之槌树人",
-- 通灵学院
["Darkmaster Gandling"] = "黑暗院长加丁",
["Instructor Malicia"] = "讲师玛丽希亚",
["Doctor Theolen Krastinov"] = "詹姆斯·哈林顿博士",
["Lorekeeper Polkelt"] = "拉文尼亚",
["Blood God"] = "血肉傀儡",
["Kormok"] = "库尔莫克",
["Alexi Barov"] = "阿雷克斯·巴罗夫",
["Illucia Barov"] = "伊露希亚·巴罗夫",
["Professor Slate"] = "瑟尔林·卡斯迪诺夫教授",
["Lady Illucia Barov"] = "马里恩·威尔逊",
["Vectus"] = "维克图斯",
["The Ravenian"] = "拉文尼亚",
["Scholomance Student"] = "通灵学员",
["Scholomance Dark Summoner"] = "通灵黑暗召唤师",
["Scholomance Skeleton"] = "通灵骷髅",
["Scholomance Undead"] = "通灵亡灵",
-- 斯坦索姆
["Baron Rivendare"] = "瑞文戴尔男爵",
["Ramstein the Gorger"] = "吞咽者拉姆斯登",
["The Unforgiven"] = "不可宽恕者",
["Baroness Anastari"] = "安娜丝塔丽男爵夫人",
["Maleki the Pallid"] = "苍白的玛勒基",
["Postmaster Malown"] = "邮差马龙",
["Archivist Galford"] = "档案管理员加尔福特",
["Timmy the Cruel"] = "提米",
["Lord Aurius Rivendare"] = "奥里克斯·瑞文戴尔领主",
["Stratholme Necromancer"] = "斯坦索姆亡灵法师",
["Stratholme Bloodletter"] = "斯坦索姆吸血者",
["Stratholme Undead"] = "斯坦索姆亡灵",
["Stratholme Ghost"] = "斯坦索姆鬼魂",
-- 黑石塔下层
["Overlord Wyrmthalak"] = "维姆萨拉克",
["Shadow Hunter Vosh'gajin"] = "暗影猎手沃什加斯",
["War Master Voone"] = "指挥官沃恩",
["Highlord Omokk"] = "欧莫克大王",
["Goraluk Anvilcrack"] = "尖石统帅",
["Smolderweb"] = "烟网蜘蛛领主",
["Urok Doomhowl"] = "乌洛克",
["Crystal Fang"] = "水晶之牙",
["Bannok Grimaxe"] = "班诺克·巨拳",
["Halycon"] = "哈雷肯",
["Blackrock Spire Mage"] = "黑石尖塔法师",
["Blackrock Dragonspawn"] = "黑石龙人",
["Blackrock Orc"] = "黑石兽人",
["Blackrock Worg"] = "黑石座狼",

-- ========== 乌龟服新增副本怪物 ==========
-- 新月林地
["Grovetender Engryss"] = "林地守护者·恩格瑞斯",
["Keeper Ranathos"] = "塞纳留斯之子·拉纳索斯",
["High Priestess A'lathea"] = "高等女祭司·阿莱萨",
["Fenektis the Deceiver"] = "欺诈者·菲内克提斯",
["The Ancient Guardian"] = "远古守护者",
["Moonlight Furbolg"] = "月光熊怪",
["Corrupted Treant"] = "腐化树人",
["Grove Guardian"] = "林地守卫",
["Moonlight Spirit"] = "月光精灵",
-- 风暴废墟
["Olurok the Heartbreaker"] = "欧鲁诺克·裂心",
["Dargal the Glutton"] = "暴食者·达加尔",
["Duke Barlow IV"] = "巴洛公爵四世",
["Theodorus the Librarian"] = "图书管理员西奥多鲁斯",
["Chieftain Rage"] = "雷歌酋长",
["Deathlord Tedben"] = "死亡领主·泰德贝恩",
["Harthas Shadowcrown the Conqueror"] = "征服者·哈尔萨斯·暗影之冠",
["Myserakus"] = "麦塞拉克斯",
["Ancient Old Maw"] = "原始的老喉巨鳄",
["Lady Drazal"] = "德拉扎尔女士",
["Remains of the Innocent"] = "无辜者的遗骸",
["Murggos"] = "墨苟斯",
["Storm Museum Guard"] = "风暴博物馆守卫",
["Barlo Undead"] = "巴洛亡灵",
["Storm Elemental"] = "风暴元素",
["Ruins Keeper"] = "废墟看守",
-- 龙喉居所
["Argolon Fragment Keeper"] = "阿尔戈隆碎片守护者",
["Dathrognar Fragment Collector"] = "达斯罗纳格碎片收集者",
["Flamekeeper"] = "护火者",
["Webmaster"] = "织网大师",
["Den Weaver Queen"] = "穴织女王",
["Elder Bloodvoid"] = "长者空血",
["Slagfist Destroyer"] = "渣拳毁灭者",
["Dwarf Ancestral Spirit"] = "矮人先祖之魂",
["Serisatassa"] = "希瑞丝塔萨",
["Dragonmaw Commander Grukk"] = "龙喉指挥官·格鲁克",
["Gnoll Overseer"] = "豺狼人工头",
["Darkheart King"] = "黑心大王",
["Halgan Redmark"] = "哈尔甘·红标",
["Karlok Flamekeeper"] = "卡洛克·护火者",
["Solitary Peak"] = "孤峰",
["Gnoll Miner"] = "豺狼人矿工",
["Dragonmaw Grunt"] = "龙喉步兵",
["Dragonmaw Mage"] = "龙喉法师",
["Dragonmaw Handler"] = "龙喉驭龙者",
["Cave Spider"] = "穴居蜘蛛",
["Fire Elemental"] = "火焰元素",
-- 卡拉赞地穴
["Gnawer the Grave"] = "嚼尸鬼",
["Cultist Warlock"] = "诅咒教派巫师",
["Hivaxxis Corpsemucher"] = "骸骨编织者",
["Guard Captain Gort"] = "卫兵队长戈特",
["Archlich Enkhraz"] = "大巫妖安克拉兹",
["Chandelier Guardian"] = "倒吊深渊守卫",
["Imp Shadowweaver"] = "劣魔影织者",
["Imp Primal Hunter"] = "劣魔原猎者",
["Imp Magister"] = "劣魔魔导师",
["Forgotten Keeper"] = "被遗忘的看守者",
["Upside-Down Bat"] = "倒吊深渊蝙蝠",
["Hungry Deathcreeper"] = "饥饿的死催戈",
["Karazhan Ghoul"] = "卡拉赞食尸鬼",
["Karazhan Wraith"] = "卡拉赞怨灵",
["Moros Lubbock"] = "莫罗斯·卢布克",
-- 风角峡谷
["Parthan Duskhide"] = "帕斯恩·暮皮",
["Agtus the Pure"] = "纯洁者阿格图斯",
["Ambassador Voltalus"] = "沃尔塔卢大使",
["Valgen Bloodcaller"] = "瓦尔根·唤血者",
["Narglem the Bonespeaker"] = "骨语者纳尔格姆",
["Thunderhorn"] = "雷角",
["Chieftain Darkwind Sharke"] = "黑风酋长沙尔克",
["Darkwind Warrior"] = "黑风部族战士",
["Windshear Hunter"] = "风啸部族猎手",
["Darkwind Shaman"] = "黑风萨满",
["Darkwind Brute"] = "黑风蛮兵",
["Windhorn Raptor"] = "风角猛禽",
["Grimtotem Behemoth"] = "恐怖图腾巨兽",
-- 暴风城大监狱
["Azosh Coldflame"] = "阿索什·冷焰",
["Samgral"] = "萨姆格拉尔",
["Lady Dark"] = "黑暗夫人",
["Damian"] = "达米安",
["Volren"] = "沃尔伦",
["Akthelas"] = "阿克提拉斯",
["Prison Warden"] = "监狱守卫",
["Corrupted Mage"] = "腐化法师",
["Stormwind Jailer"] = "暴风城狱卒",
["Prison Inmate"] = "监狱囚犯",
["Jail Fire Imp"] = "狱火妖",
["Dark Guardian"] = "黑暗护卫",
-- 吉尔尼斯城
["Genn Greymane"] = "吉恩·格雷迈恩",
["Regent Mortimer Harlow"] = "摄政王莫蒂默·哈洛",
["Celia Harlow"] = "西莉亚·哈洛",
["Dustivan Blackcall"] = "达斯蒂万·布莱克考尔",
["Liam Greymane"] = "利亚姆·格雷迈恩",
["Roseman"] = "罗斯曼",
["Gilnean Worgen"] = "吉尔尼斯狼人",
["Gilnean Guard"] = "吉尔尼斯守卫",
["Gilnean Soldier"] = "吉尔尼斯士兵",
["Gilnean Undead"] = "吉尔尼斯亡灵",
-- 黑色沼泽
["Chrona"] = "克罗纳",
["Echo of Time"] = "时间的回音",
["Epidamus"] = "埃皮达姆",
["Antinomy"] = "安蒂诺米",
["Time Warper"] = "时间扭曲者",
["Void Ripper"] = "虚空撕裂者",
["Temporal Dragon"] = "时湮龙",
["Eternal Walker"] = "永恒行者",
["Time Thief"] = "时间窃贼",
["Void Walker"] = "虚空行者",
["Rift Wanderer"] = "裂隙漫游者",
-- 木喉要塞
["Sentinel Kash"] = "哨兵卡什",
["Rot Howl"] = "腐嚎",
["Three-Headed Serpent"] = "三头蛇",
["Earthsplitter Omannos"] = "裂地者欧曼诺斯",
["Fallen"] = "落潭",
["Great Chieftain Parthas"] = "大酋长帕萨斯",
["Selenarx Rotheart"] = "塞雷纳克斯·腐心",
["Archdruid Koron"] = "大德鲁伊科罗恩",
["Ursol"] = "乌索尔",
["Perotharn"] = "佩罗萨恩",
["Timbermaw Furbolg"] = "木喉熊怪",
["Timbermaw Guardian"] = "木喉守卫",
-- 翡翠圣殿
["Eranius"] = "埃雷纽斯",
["Awakener Thor'nius"] = "觉醒者索尔纽斯",
["Sanctum Dream Wanderer"] = "圣所梦游者",
["Sanctum Suppressor"] = "圣所压制者",
["Sanctum Drake"] = "圣所龙族",
-- 塔纳利斯新副本
["Grand Traveler"] = "大旅行家",
["Sand Eater"] = "食沙者",
["Dust Lord"] = "沙尘领主",
["Desert Guardian"] = "沙漠守护者",
["Desert Hunter"] = "沙漠猎人",
-- 奥达曼新增区域
["Stone Guardian"] = "石像守卫",

-- ========== 乌龟服全域稀有精英 ==========
["All-Seeing Zakk"] = "全视者扎克",
["Blackrock Stomper"] = "黑石践踏者",
["Lava Guardian"] = "熔岩守护者",
["Lord Garatek"] = "加泰克领主",
["Nathas"] = "纳萨斯",
["Ravager Talon"] = "掠夺者爪兽",
["Shadowreaper"] = "恶魔收割者",

-- ========== 卫兵（联盟/部落/中立） ==========
["Stormwind Guard"] = "暴风城卫兵",
["Ironforge Guard"] = "铁炉堡卫兵",
["Darnassus Sentinel"] = "达纳苏斯哨兵",
["Theramore Guard"] = "塞拉摩卫兵",
["Orgrimmar Grunt"] = "奥格瑞玛步兵",
["Undercity Guard"] = "幽暗城卫兵",
["Thunder Bluff Protector"] = "雷霆崖守护者",
["Gadgetzan Enforcer"] = "加基森治安官",
["Booty Bay Guard"] = "藏宝海湾卫兵",
["Ratchet Guard"] = "棘齿城卫兵",
["Gadgetzan Grunt"] = "地精卫兵",
["Gadgetzan Peacekeeper"] = "地精执法者",
["Northridge Defender"] = "北风岭守卫",
["Moonglade Sentinel"] = "月语海岸哨兵",
}

-- ========== PVP判定字典 ==========
TDL_PvP_NPC_Dict = {
    -- 原有
    ["Defias Bodyguard"] = true, ["迪菲亚保镖"] = true,
    -- 联盟卫兵
    ["Stormwind Guard"] = true, ["暴风城卫兵"] = true,
    ["Ironforge Guard"] = true, ["铁炉堡卫兵"] = true,
    ["Darnassus Sentinel"] = true, ["达纳苏斯哨兵"] = true,
    ["Theramore Guard"] = true, ["塞拉摩卫兵"] = true,
    -- 部落卫兵
    ["Orgrimmar Grunt"] = true, ["奥格瑞玛步兵"] = true,
    ["Undercity Guard"] = true, ["幽暗城卫兵"] = true,
    ["Thunder Bluff Protector"] = true, ["雷霆崖守护者"] = true,
    -- 中立城市卫兵
    ["Gadgetzan Enforcer"] = true, ["加基森治安官"] = true,
    ["Booty Bay Guard"] = true, ["藏宝海湾卫兵"] = true,
    ["Ratchet Guard"] = true, ["棘齿城卫兵"] = true,
    ["Gadgetzan Grunt"] = true, ["地精卫兵"] = true,
    ["Gadgetzan Peacekeeper"] = true, ["地精执法者"] = true,
    -- 乌龟服特有区域卫兵
    ["Northridge Defender"] = true, ["北风岭守卫"] = true,
    ["Moonglade Sentinel"] = true, ["月语海岸哨兵"] = true,
}

-- ==========================================================
-- ========== 临时翻译区域 ==========
-- 在这里添加您平时遇到但字典里没有的临时中英对照。
-- 格式： ["英文名"] = "中文名",
-- 注意：不要忘记结尾的逗号！
-- ==========================================================

-- ==========================================================
-- 临时地名区
-- ==========================================================
TDL_TempZoneDict = {
    -- 例如: ["New City"] = "新城",
    ["Irontree Woods"] = "铁木森林",
    ["Shatter Scar Vale"] = "碎痕谷",
    ["Twilight Vale"] = "暮光谷",
    ["Lakeridge Highway"] = "湖畔大道",
}

-- ==========================================================
-- 临时怪物区
-- ==========================================================
TDL_TempNPCDict = {
    -- 例如: ["New Boar"] = "新野猪",
    ["Ribchaser"] = "追肋者",
    ["Xalvic Blackclaw"] = "扎尔维克·黑爪",
    ["Kroshius"] = "克罗休斯",
    ["Strider Clutchmother"] = "陆行鸟巢母",
    ["Murloc Shorestriker"] = "海岸鱼人打击者",
    ["Foreman Grills"] = "工头格里尔斯",
}

-- 核心翻译引擎 (已升级支持独立的临时地名和临时怪物字典)
function TDL_Translate(text, dictType)
    if not text then return "未知" end
    
    if dictType == "ZONE" then
        if TDL_TempZoneDict and TDL_TempZoneDict[text] then return TDL_TempZoneDict[text] end
        return TDL_ZoneDict[text] or text
    else
        if TDL_TempNPCDict and TDL_TempNPCDict[text] then return TDL_TempNPCDict[text] end
        return TDL_NPCDict[text] or text
    end
end
